# Generated by Django 3.1.2 on 2020-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
