# Generated by Django 3.1.2 on 2020-11-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_diary', '0007_auto_20201107_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=50)),
                ('check', models.IntegerField()),
                ('writer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_diary.user')),
            ],
        ),
    ]
