# Generated by Django 3.1.2 on 2020-11-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_diary', '0008_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='check',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
