# Generated by Django 3.1.2 on 2020-11-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_diary', '0009_auto_20201108_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
    ]
