# Generated by Django 3.1.2 on 2020-11-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_diary', '0012_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_public',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_date', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed', to='study_diary.user')),
                ('following', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to='study_diary.user')),
            ],
        ),
    ]
